# Generated by Django 6.1 on 2026-08-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
